[images]
  remote_images = [
    "https://ext.same-assets.com/.*"
  ]

[build]
  command = "npm install -g bun && bun install && bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173
  framework = "#custom"
